compila_mp:

ayuda_mp:
	julia FrioCalor.jl -h

ejecuta_mp:
	julia FrioCalor.jl --input_file input_mp.txt --output_file output_mp.txt 

compilar:

ayuda_perceptron:
	julia Perceptron.jl -h

ejecuta_perceptron:
	julia Perceptron.jl --input_file problema_real1.txt --output_file prediccion_perceptron.txt --umbral 0.2 --tasa_aprendizaje 1 --max_epocas 11 --modo 1 --porcentaje 0.2

ayuda_adaline:
	julia Adaline.jl -h

ejecuta_adaline:
	julia Adaline.jl --input_file problema_real1.txt --output_file prediccion_adaline.txt --tasa_aprendizaje 1 --max_epocas 11 --tolerancia 0.2 --modo 1 --porcentaje 0.2