compilar:

ayuda_perceptron:
	julia Perceptron.jl -h

ejecuta_perceptron:
	julia Perceptron.jl --input_file Datos\problema_real1.txt --output_file perceptron_output.txt --umbral 0.2 --tasa_aprendizaje 1 --max_epocas 11 --modo 1 --porcentaje 0.2

ayuda_adaline:
	julia Adaline.jl -h

ejecuta_adaline:
	julia Adaline.jl --input_file Datos\problema_real1.txt --output_file adaline_output.txt --tasa_aprendizaje 1 --max_epocas 11 --tolerancia 0.2 --modo 1 --porcentaje 0.2